### ISSUE TITLE
Use auto-refillable addresses in network tests

### ISSUE THREAD

**Issue by rvem** [tz-wrapped/tezos-btc#173]
# Clarification and motivation
Networks tests tend to fail due to insufficient balance errors. `cleveland` recently introduced auto-refillable addresses,
which are probably going to help us to avoid hardcoding transfer amounts in the code.

# Acceptance criteria
Network tests don't use hardcoded transfer amounts.

**Comment by lierdakil** [comment]
Uh. So there's a problem. IIUC, the primary place where this is required is smoke tests. But smoke tests run through tzbtc-client. Obviously, running through tzbtc-client doesn't engage the refillable machinery (since the transfer doesn't go through Cleveland at all). It seems we really can't escape _some_ hard-coding.
